import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { DicesIcon } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex items-center justify-center h-screen flex flex-col space-y-4">
        <h2 className="text-3xl font-semibold flex flex-row">
          Random Public API <DicesIcon />
        </h2>
        {children}
      </body>
    </html>
  );
}
